### ISSUE TITLE
Having trouble running go get github.com/myodc/micro

### ISSUE THREAD

**Issue by abhinavzspace** [myodc/micro#2]
I am using ubuntu 14.04, go version 1.4
Here are the error details:
github.com/myodc/go-micro/registry/kubernetes
/home/abhi/.gvm/pkgsets/go1.4/global/src/github.com/myodc/go-micro/registry/kubernetes/kubernetes.go:60: item.Spec.PortalIP undefined (type "github.com/GoogleCloudPlatform/kubernetes/pkg/api".ServiceSpec has no field or method PortalIP)
/home/abhi/.gvm/pkgsets/go1.4/global/src/github.com/myodc/go-micro/registry/kubernetes/watcher.go:29: svc.Spec.PortalIP undefined (type "github.com/GoogleCloudPlatform/kubernetes/pkg/api".ServiceSpec has no field or method PortalIP)

**Comment by asim** [comment]
Hi, looks like there was a change in the kubernetes api package. Should be fixed now.
